######################################################################################
# Here are some important quotes from famous philosophers that everyone should know. #
######################################################################################

quotes = [
    ("Socrates", "The unexamined life is not worth living."),
    ("Socrates", "I know that I am intelligent, because I know that I know nothing."),
    ("Plato", "Ideas are the ultimate reality."),
    ("Plato", "The measure of a man is what he does with power."),
    ("Aristotle", "Happiness is the meaning and the purpose of life, the whole aim and end of human existence."),
    ("Aristotle", "It is the mark of an educated mind to be able to entertain a thought without accepting it."),
    ("Epicurus", "Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for."),
    ("Epicurus", "Not what we have but what we enjoy, constitutes our abundance."),
    ("Seneca", "It is not that we have a short time to live, but that we waste a lot of it."),
    ("Seneca", "Luck is what happens when preparation meets opportunity."),
    ("Marcus Aurelius", "The happiness of your life depends upon the quality of your thoughts."),
    ("Marcus Aurelius", "The universe is transformation, life is opinion."),
    ("Epictetus", "It's not what happens to you, but how you react to it that matters."),
    ("Epictetus", "Wealth consists not in having great possessions, but in having few wants."),
    ("Augustine", "Faith is to believe what you do not see; the reward of this faith is to see what you believe."),
    ("Augustine", "Love God and do what you will."),
    ("Thomas Aquinas", "To one who has faith, no explanation is necessary. To one without faith, no explanation is possible."),
    ("Thomas Aquinas", "The things that we love tell us what we are."),
    ("Descartes", "I think, therefore I am."),
    ("Descartes", "To live without philosophizing is in truth the same as keeping the eyes closed without attempting to open them."),
    ("Spinoza", "The highest activity a human being can attain is learning for understanding, because to understand is to be free."),
    ("Spinoza", "Peace is not the absence of war, but a virtue based on strength of character."),
    ("Leibniz", "This is the best of all possible worlds."),
    ("Leibniz", "The present is full of the future."),
    ("Locke", "No man's knowledge here can go beyond his experience."),
    ("Locke", "Where there is no law, there is no freedom."),
    ("Hume", "Reason is, and ought only to be the slave of the passions."),
    ("Hume", "The life of man is of no greater importance to the universe than that of an oyster."),
    ("Rousseau", "Man is born free, and everywhere he is in chains."),
    ("Rousseau", "The world of reality has its limits; the world of imagination is boundless."),
    ("Kant", "Act only according to that maxim whereby you can at the same time will that it should become a universal law."),
    ("Kant", "Science is organized knowledge. Wisdom is organized life."),
    ("Kant", "Two things fill the mind with ever new and increasing admiration and awe: the starry heavens above me and the moral law within me."),
    ("Hegel", "The only thing we learn from history is that we learn nothing from history."),
    ("Hegel", "What is rational is actual and what is actual is rational."),
    ("Schopenhauer", "Life is a constant process of dying."),
    ("Schopenhauer", "A man can be himself only so long as he is alone."),
    ("Nietzsche", "He who has a why to live can bear almost any how."),
    ("Nietzsche", "Without music, life would be a mistake."),
    ("Nietzsche", "What does not kill me makes me stronger."),
    ("Kierkegaard", "Life can only be understood backwards; but it must be lived forwards."),
    ("Kierkegaard", "The most common form of despair is not being who you are."),
    ("Kierkegaard", "Anxiety is the dizziness of freedom."),
    ("Marx", "The philosophers have only interpreted the world, in various ways; the point is to change it."),
    ("Marx", "Workers of the world, unite!"),
    ("John Stuart Mill", "The only freedom which deserves the name is that of pursuing our own good in our own way."),
    ("John Stuart Mill", "It is better to be a human being dissatisfied than a pig satisfied; better to be Socrates dissatisfied than a fool satisfied."),
    ("William James", "The greatest weapon against stress is our ability to choose one thought over another."),
    ("William James", "Act as if what you do makes a difference. It does."),
    ("Bertrand Russell", "The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts."),
    ("Bertrand Russell", "To be without some of the things you want is an indispensable part of happiness."),
    ("Wittgenstein", "The limits of my language mean the limits of my world."),
    ("Wittgenstein", "Whereof one cannot speak, thereof one must be silent."),
    ("Heidegger", "Being is time."),
    ("Heidegger", "Man is not the lord of beings, but the shepherd of Being."),
    ("Sartre", "Hell is other people."),
    ("Sartre", "Existence precedes essence."),
    ("Camus", "In the depth of winter, I finally learned that within me there lay an invincible summer."),
    ("Camus", "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion."),
    ("Popper", "Science is not a system of certain, or well-established, statements; it is never a finished system."),
    ("Popper", "Our whole point in science is to be able to predict."),
    ("Kuhn", "The history of science is a history of scientific revolutions."),
    ("Foucault", "Power is everywhere; not because it embraces everything, but because it comes from everywhere."),
    ("Foucault", "We are freer than we feel."),
    ("Derrida", "There is nothing outside the text."),
    ("Derrida", "The absence of the transcendental signified extends the domain and the play of signification infinitely."),
    ("Rorty", "Truth is what your contemporaries let you get away with."),
    ("Arendt", "The banality of evil."),
    ("Arendt", "To think and to be free are the same thing."),
    ("Simone de Beauvoir", "One is not born, but rather becomes, a woman."),
    ("Simone de Beauvoir", "That the woman is the Other means that she is not the subject."),
    ("Adorno", "The whole is the false."),
    ("Horkheimer", "Enlightenment is totalitarian."),
    ("Marcuse", "One-dimensional man."),
    ("Fromm", "The task of being human is to be a person."),
    ("Buber", "All real living is meeting."),
    ("Karl Jaspers", "The great decisions of human life have to do with the choice of one's own self."),
    ("Simone Weil", "Attention is the rarest and purest form of generosity."),
    ("Simone Weil", "The love of truth is the love of the good."),
    ("Žižek", "The real is the impossible."),
    ("Žižek", "We are not allowed to be happy, we are only allowed to be satisfied."),
    ("Nussbaum", "To be a good human being is to have a kind of openness to the world, an ability to trust uncertain things beyond your own control."),
    ("Nussbaum", "The idea of dignity is that humans are ends in themselves."),
    ("Dennett", "There is no such thing as consciousness without a brain."),
    ("Dennett", "The secret of happiness is: find something more important than you are and dedicate your life to it."),
    ("Judith Butler", "Gender is not a fact, but a performance."),
    ("Judith Butler", "To be a woman is to be in a state of becoming."),
    ("Peter Singer", "The only thing that is good is the satisfaction of preferences."),
    ("Peter Singer", "We need to expand our moral circle to include all sentient beings."),
    ("Thomas Nagel", "The mind-body problem is the problem of understanding how the subjective character of experience can exist."),
    ("Thomas Nagel", "We are not just parts of the world; we are also centers of it."),
    ("Hilary Putnam", "The meaning of a term is determined by the way the term is used."),
    ("Hilary Putnam", "The mind is not a computer."),
    ("John Searle", "The Chinese room argument shows that syntax is not sufficient for semantics."),
    ("John Searle", "Consciousness is a biological phenomenon."),
    ("Alain Badiou", "Truth is a process of fidelity to an event."),
    ("Bruno Latour", "We have never been modern."),
    ("Gilles Deleuze", "The future is the virtual, which we must actualize."),
    ("Michel Serres", "The difference between the human and the animal is that the human has a history."),
    ("Emmanuel Levinas", "The face of the Other is the ethical call."),
    ("Daniil Shitov", "Eshte!"),
    ("Socrates", "Wonder is the beginning of wisdom."),
    ("Plato", "Knowledge is the food of the soul."),
    ("Aristotle", "Knowing yourself is the beginning of all wisdom."),
    ("Epicurus", "If you wish to be rich, do not add to your money but subtract from your desires."),
    ("Seneca", "Difficulties strengthen the mind, as labor does the body."),
    ("Marcus Aurelius", "Waste no more time arguing what a good man should be. Be one."),
    ("Epictetus", "No man is free who is not master of himself."),
    ("Augustine", "The world is a book, and those who do not travel read only one page."),
    ("Thomas Aquinas", "There is nothing on this earth more to be prized than true friendship."),
    ("Descartes", "Divide each difficulty into as many parts as is feasible and necessary to resolve it."),
    ("Spinoza", "All things excellent are as difficult as they are rare."),
    ("Leibniz", "Music is the pleasure the human soul experiences from counting without being aware that it is counting."),
    ("Locke", "Reading furnishes the mind only with materials of knowledge."),
    ("Hume", "Beauty in things exists merely in the mind which contemplates them."),
    ("Rousseau", "Patience is bitter, but its fruit is sweet."),
    ("Kant", "Dare to know! Have the courage to use your own understanding."),
    ("Hegel", "Nothing great in the world has ever been accomplished without passion."),
    ("Schopenhauer", "Compassion is the basis of morality."),
    ("Nietzsche", "Become who you are."),
    ("Kierkegaard", "The function of prayer is not to influence God, but rather to change the nature of the one who prays."),
    ("Marx", "History repeats itself, first as tragedy, second as farce."),
    ("John Stuart Mill", "The worth of a state, in the long run, is the worth of the individuals composing it."),
    ("William James", "Believe that life is worth living and your belief will help create the fact."),
    ("Bertrand Russell", "Fear is the main source of superstition."),
    ("Wittgenstein", "A picture is a fact."),
    ("Heidegger", "Language is the house of Being."),
    ("Sartre", "Freedom is what you do with what's been done to you."),
    ("Sartre", "Man is condemned to be free."),
    ("Camus", "Should I kill myself, or have a cup of coffee?"),
    ("Popper", "All life is problem solving."),
    ("Kuhn", "Paradigms gain their status because they are more successful than their competitors."),
    ("Foucault", "Knowledge is not made for understanding; it is made for cutting."),
    ("Derrida", "Every text participates in one or several genres."),
    ("Rorty", "Take care of freedom and truth will take care of itself."),
    ("Arendt", "Forgiveness is the key to action and freedom."),
    ("Simone de Beauvoir", "Change your life today. Do not gamble on the future."),
    ("Adorno", "Wrong life cannot be lived rightly."),
    ("Horkheimer", "Whoever is not willing to talk about capitalism should also keep quiet about fascism."),
    ("Marcuse", "Free election of masters does not abolish the masters or the slaves."),
    ("Fromm", "Love is the only sane and satisfactory answer to the problem of human existence."),
    ("Buber", "An animal's eyes have the power to speak a great language."),
    ("Karl Jaspers", "Philosophy means to be on the way."),
    ("Simone Weil", "Imaginary evil is romantic and varied; real evil is gloomy and monotonous."),
    ("Žižek", "Words are never only words."),
    ("Nussbaum", "Compassion is an unstable emotion unless it is grounded in thought."),
    ("Dennett", "There is no such thing as philosophy-free science."),
    ("Judith Butler", "We lose ourselves in what we read, only to return to ourselves transformed."),
    ("Peter Singer", "If it is in our power to prevent something bad without sacrificing anything of comparable importance, we ought to do it."),
    ("Thomas Nagel", "Viewpoints are essential to understanding reality."),
    ("Hilary Putnam", "Meaning just ain't in the head."),
    ("John Searle", "Speech acts are the basic units of communication."),
    ("Karl Jaspers"), "Philosophy does not show new objects, but shows all objects in a new way.",
    ("Alain Badiou", "Love is the minimal form of communism."),
    ("Bruno Latour", "Technology is society made durable."),
    ("Gilles Deleuze", "Repetition changes nothing in the object repeated, but does change something in the mind that contemplates it."),
    ("Michel Serres", "Learning means inventing."),
    ("Natalya Kaplanskaya"), "Don't explain the explainable",
    ("Emmanuel Levinas", "Ethics is first philosophy."),
    ("Thomas Nagel", "What does it mean to be a bat?"),
]
