######################################################################################
# Here are some important quotes from famous philosophers that everyone should know. #
######################################################################################

quotes = [
    ("Socrates", "The unexamined life is not worth living."),
    ("Socrates", "I know that I am intelligent, because I know that I know nothing."),
    ("Plato", "Ideas are the ultimate reality."),
    ("Plato", "The measure of a man is what he does with power."),
    ("Aristotle", "Happiness is the meaning and the purpose of life, the whole aim and end of human existence."),
    ("Aristotle", "It is the mark of an educated mind to be able to entertain a thought without accepting it."),
    ("Epicurus", "Do not spoil what you have by desiring what you have not; remember that what you now have was once among the things you only hoped for."),
    ("Epicurus", "Not what we have but what we enjoy, constitutes our abundance."),
    ("Seneca", "It is not that we have a short time to live, but that we waste a lot of it."),
    ("Seneca", "Luck is what happens when preparation meets opportunity."),
    ("Marcus Aurelius", "The happiness of your life depends upon the quality of your thoughts."),
    ("Marcus Aurelius", "The universe is transformation, life is opinion."),
    ("Epictetus", "It's not what happens to you, but how you react to it that matters."),
    ("Epictetus", "Wealth consists not in having great possessions, but in having few wants."),
    ("Augustine", "Faith is to believe what you do not see; the reward of this faith is to see what you believe."),
    ("Augustine", "Love God and do what you will."),
    ("Thomas Aquinas", "To one who has faith, no explanation is necessary. To one without faith, no explanation is possible."),
    ("Thomas Aquinas", "The things that we love tell us what we are."),
    ("Descartes", "I think, therefore I am."),
    ("Descartes", "To live without philosophizing is in truth the same as keeping the eyes closed without attempting to open them."),
    ("Spinoza", "The highest activity a human being can attain is learning for understanding, because to understand is to be free."),
    ("Spinoza", "Peace is not the absence of war, but a virtue based on strength of character."),
    ("Leibniz", "This is the best of all possible worlds."),
    ("Leibniz", "The present is full of the future."),
    ("Locke", "No man's knowledge here can go beyond his experience."),
    ("Locke", "Where there is no law, there is no freedom."),
    ("Hume", "Reason is, and ought only to be the slave of the passions."),
    ("Hume", "The life of man is of no greater importance to the universe than that of an oyster."),
    ("Rousseau", "Man is born free, and everywhere he is in chains."),
    ("Rousseau", "The world of reality has its limits; the world of imagination is boundless."),
    ("Kant", "Act only according to that maxim whereby you can at the same time will that it should become a universal law."),
    ("Kant", "Science is organized knowledge. Wisdom is organized life."),
    ("Kant", "Two things fill the mind with ever new and increasing admiration and awe: the starry heavens above me and the moral law within me."),
    ("Hegel", "The only thing we learn from history is that we learn nothing from history."),
    ("Hegel", "What is rational is actual and what is actual is rational."),
    ("Schopenhauer", "Life is a constant process of dying."),
    ("Schopenhauer", "A man can be himself only so long as he is alone."),
    ("Nietzsche", "He who has a why to live can bear almost any how."),
    ("Nietzsche", "Without music, life would be a mistake."),
    ("Nietzsche", "What does not kill me makes me stronger."),
    ("Kierkegaard", "Life can only be understood backwards; but it must be lived forwards."),
    ("Kierkegaard", "The most common form of despair is not being who you are."),
    ("Kierkegaard", "Anxiety is the dizziness of freedom."),
    ("Marx", "The philosophers have only interpreted the world, in various ways; the point is to change it."),
    ("Marx", "Workers of the world, unite!"),
    ("John Stuart Mill", "The only freedom which deserves the name is that of pursuing our own good in our own way."),
    ("John Stuart Mill", "It is better to be a human being dissatisfied than a pig satisfied; better to be Socrates dissatisfied than a fool satisfied."),
    ("William James", "The greatest weapon against stress is our ability to choose one thought over another."),
    ("William James", "Act as if what you do makes a difference. It does."),
    ("Bertrand Russell", "The whole problem with the world is that fools and fanatics are always so certain of themselves, and wiser people so full of doubts."),
    ("Bertrand Russell", "To be without some of the things you want is an indispensable part of happiness."),
    ("Wittgenstein", "The limits of my language mean the limits of my world."),
    ("Wittgenstein", "Whereof one cannot speak, thereof one must be silent."),
    ("Heidegger", "Being is time."),
    ("Heidegger", "Man is not the lord of beings, but the shepherd of Being."),
    ("Sartre", "Hell is other people."),
    ("Sartre", "Existence precedes essence."),
    ("Camus", "In the depth of winter, I finally learned that within me there lay an invincible summer."),
    ("Camus", "The only way to deal with an unfree world is to become so absolutely free that your very existence is an act of rebellion."),
    ("Popper", "Science is not a system of certain, or well-established, statements; it is never a finished system."),
    ("Popper", "Our whole point in science is to be able to predict."),
    ("Kuhn", "The history of science is a history of scientific revolutions."),
    ("Foucault", "Power is everywhere; not because it embraces everything, but because it comes from everywhere."),
    ("Foucault", "We are freer than we feel."),
    ("Derrida", "There is nothing outside the text."),
    ("Derrida", "The absence of the transcendental signified extends the domain and the play of signification infinitely."),
    ("Rorty", "Truth is what your contemporaries let you get away with."),
    ("Arendt", "The banality of evil."),
    ("Arendt", "To think and to be free are the same thing."),
    ("Simone de Beauvoir", "One is not born, but rather becomes, a woman."),
    ("Simone de Beauvoir", "That the woman is the Other means that she is not the subject."),
    ("Adorno", "The whole is the false."),
    ("Horkheimer", "Enlightenment is totalitarian."),
    ("Marcuse", "One-dimensional man."),
    ("Fromm", "The task of being human is to be a person."),
    ("Buber", "All real living is meeting."),
    ("Karl Jaspers", "The great decisions of human life have to do with the choice of one's own self."),
    ("Simone Weil", "Attention is the rarest and purest form of generosity."),
    ("Simone Weil", "The love of truth is the love of the good."),
    ("Žižek", "The real is the impossible."),
    ("Žižek", "We are not allowed to be happy, we are only allowed to be satisfied."),
    ("Nussbaum", "To be a good human being is to have a kind of openness to the world, an ability to trust uncertain things beyond your own control."),
    ("Nussbaum", "The idea of dignity is that humans are ends in themselves."),
    ("Dennett", "There is no such thing as consciousness without a brain."),
    ("Dennett", "The secret of happiness is: find something more important than you are and dedicate your life to it."),
    ("Judith Butler", "Gender is not a fact, but a performance."),
    ("Judith Butler", "To be a woman is to be in a state of becoming."),
    ("Peter Singer", "The only thing that is good is the satisfaction of preferences."),
    ("Peter Singer", "We need to expand our moral circle to include all sentient beings."),
    ("Thomas Nagel", "The mind-body problem is the problem of understanding how the subjective character of experience can exist."),
    ("Thomas Nagel", "We are not just parts of the world; we are also centers of it."),
    ("Hilary Putnam", "The meaning of a term is determined by the way the term is used."),
    ("Hilary Putnam", "The mind is not a computer."),
    ("John Searle", "The Chinese room argument shows that syntax is not sufficient for semantics."),
    ("John Searle", "Consciousness is a biological phenomenon."),
    ("Alain Badiou", "Truth is a process of fidelity to an event."),
    ("Bruno Latour", "We have never been modern."),
    ("Gilles Deleuze", "The future is the virtual, which we must actualize."),
    ("Michel Serres", "The difference between the human and the animal is that the human has a history."),
    ("Emmanuel Levinas", "The face of the Other is the ethical call."),
    ("Daniil Shitov", "Eshte!"),
    ("Socrates", "Wonder is the beginning of wisdom."),
    ("Plato", "Knowledge is the food of the soul."),
    ("Aristotle", "Knowing yourself is the beginning of all wisdom."),
    ("Epicurus", "If you wish to be rich, do not add to your money but subtract from your desires."),
    ("Seneca", "Difficulties strengthen the mind, as labor does the body."),
    ("Marcus Aurelius", "Waste no more time arguing what a good man should be. Be one."),
    ("Epictetus", "No man is free who is not master of himself."),
    ("Augustine", "The world is a book, and those who do not travel read only one page."),
    ("Thomas Aquinas", "There is nothing on this earth more to be prized than true friendship."),
    ("Descartes", "Divide each difficulty into as many parts as is feasible and necessary to resolve it."),
    ("Spinoza", "All things excellent are as difficult as they are rare."),
    ("Leibniz", "Music is the pleasure the human soul experiences from counting without being aware that it is counting."),
    ("Locke", "Reading furnishes the mind only with materials of knowledge."),
    ("Hume", "Beauty in things exists merely in the mind which contemplates them."),
    ("Rousseau", "Patience is bitter, but its fruit is sweet."),
    ("Kant", "Dare to know! Have the courage to use your own understanding."),
    ("Hegel", "Nothing great in the world has ever been accomplished without passion."),
    ("Schopenhauer", "Compassion is the basis of morality."),
    ("Nietzsche", "Become who you are."),
    ("Kierkegaard", "The function of prayer is not to influence God, but rather to change the nature of the one who prays."),
    ("Marx", "History repeats itself, first as tragedy, second as farce."),
    ("John Stuart Mill", "The worth of a state, in the long run, is the worth of the individuals composing it."),
    ("William James", "Believe that life is worth living and your belief will help create the fact."),
    ("Bertrand Russell", "Fear is the main source of superstition."),
    ("Wittgenstein", "A picture is a fact."),
    ("Heidegger", "Language is the house of Being."),
    ("Jean-Paul Sartre", "Freedom is what you do with what's been done to you."),
    ("Jean-Paul Sartre", "Man is condemned to be free."),
    ("Jean-Paul Sartre", "We are our choices."),
    ("Jean-Paul Sartre", "Every word has consequences. Every silence, too."),
    ("Jean-Paul Sartre", "There may be more beautiful times, but this one is ours."),
    ("Camus", "Should I kill myself, or have a cup of coffee?"),
    ("Popper", "All life is problem solving."),
    ("Kuhn", "Paradigms gain their status because they are more successful than their competitors."),
    ("Foucault", "Knowledge is not made for understanding; it is made for cutting."),
    ("Derrida", "Every text participates in one or several genres."),
    ("Rorty", "Take care of freedom and truth will take care of itself."),
    ("Arendt", "Forgiveness is the key to action and freedom."),
    ("Simone de Beauvoir", "Change your life today. Do not gamble on the future."),
    ("Adorno", "Wrong life cannot be lived rightly."),
    ("Horkheimer", "Whoever is not willing to talk about capitalism should also keep quiet about fascism."),
    ("Marcuse", "Free election of masters does not abolish the masters or the slaves."),
    ("Fromm", "Love is the only sane and satisfactory answer to the problem of human existence."),
    ("Buber", "An animal's eyes have the power to speak a great language."),
    ("Karl Jaspers", "Philosophy means to be on the way."),
    ("Simone Weil", "Imaginary evil is romantic and varied; real evil is gloomy and monotonous."),
    ("Žižek", "Words are never only words."),
    ("Nussbaum", "Compassion is an unstable emotion unless it is grounded in thought."),
    ("Dennett", "There is no such thing as philosophy-free science."),
    ("Judith Butler", "We lose ourselves in what we read, only to return to ourselves transformed."),
    ("Peter Singer", "If it is in our power to prevent something bad without sacrificing anything of comparable importance, we ought to do it."),
    ("Thomas Nagel", "Viewpoints are essential to understanding reality."),
    ("Hilary Putnam", "Meaning just ain't in the head."),
    ("John Searle", "Speech acts are the basic units of communication."),
    ("Karl Jaspers", "Philosophy does not show new objects, but shows all objects in a new way."),
    ("Alain Badiou", "Love is the minimal form of communism."),
    ("Bruno Latour", "Technology is society made durable."),
    ("Gilles Deleuze", "Repetition changes nothing in the object repeated, but does change something in the mind that contemplates it."),
    ("Michel Serres", "Learning means inventing."),
    ("Natalya Kaplanskaya", "Don't explain the explainable"),
    ("Emmanuel Levinas", "Ethics is first philosophy."),
    ("Thomas Nagel", "What does it mean to be a bat?"),
    ("Pythagoras", "As soon as laws are necessary for men, they are no longer fit for freedom."),
    ("Pythagoras", "There is geometry in the humming of the strings, there is music in the spacing of the spheres."),

    ("Heraclitus", "No man ever steps in the same river twice."),
    ("Heraclitus", "Everything flows."),
    ("Heraclitus", "The sun is new each day."),
    ("Heraclitus", "Character is destiny."),
    ("Heraclitus", "Nature loves to hide."),
    ("Heraclitus", "Opposition brings concord."),
    ("Heraclitus", "The waking have one common world, but the sleeping turn aside each into a world of his own."),
    ("Heraclitus", "If you do not expect the unexpected, you will not find it."),

    ("Parmenides", "What is, is; what is not, cannot be."),
    ("Parmenides", "Thinking and being are the same."),
    ("Parmenides", "You cannot know what is not."),
    ("Parmenides", "For the same thing can be thought and can be."),
    ("Parmenides", "Being is ungenerated and imperishable."),
    ("Parmenides", "What can be thought and what can be are the same."),
    ("Parmenides", "It is necessary to say and to think that Being is."),
    ("Parmenides", "There are only two ways of inquiry that can be thought."),
    ("Parmenides", "Being is, and non-being is not."),
    ("Parmenides", "Change is impossible."),

    ("Diogenes", "The foundation of every state is the education of its youth."),
    ("Diogenes", "Of what use is a philosopher who doesn't hurt anybody's feelings?"),
    ("Diogenes", "There is only a finger's difference between a madman and me."),
    ("Diogenes", "The art of being a slave is to rule one's master."),
    ("Diogenes", "Why not whip yourself?"),
    ("Diogenes", "Dogs and philosophers do the greatest good and get the fewest rewards."),
    ("Diogenes", "I do not know whether there are gods, but there ought to be."),
    ("Diogenes", "The only way to avoid criticism is to do nothing, say nothing, and be nothing."),
    ("Diogenes", "I am looking for a human being."),
    ("Diogenes", "When I die, throw me over the wall, for I shall not need a grave."),

    ("Zeno of Citium", "Well-being is realized by small steps, but is truly no small thing."),
    ("Zeno of Citium", "Happiness is a good flow of life."),
    ("Zeno of Citium", "No loss should be more to us than the loss of our self-respect."),
    ("Zeno of Citium", "Better to trip with the feet than with the tongue."),
    ("Zeno of Citium", "The goal of life is living in agreement with nature."),
    ("Zeno of Citium", "Man conquers the world by conquering himself."),
    ("Zeno of Citium", "The reason why we have two ears and only one mouth is that we may hear more and speak less."),
    ("Zeno of Citium", "A bad feeling is a commotion of the mind repugnant to reason."),
    ("Zeno of Citium", "We have two ears and one mouth, so we should listen more than we say."),
    ("Zeno of Citium", "Steel your sensibilities, so that life shall hurt you as little as possible."),

    ("Cleanthes", "Lead me, Zeus, and you, Destiny, wherever you have assigned me to go."),
    ("Cleanthes", "Fate guides the willing, but drags the unwilling."),
    ("Cleanthes", "Nothing happens by chance; everything happens for a reason."),
    ("Cleanthes", "The stars are the writings of the gods."),
    ("Cleanthes", "The universe is governed by reason."),
    ("Cleanthes", "The wise man follows nature."),
    ("Cleanthes", "The beginning of wisdom is to understand necessity."),
    ("Cleanthes", "Virtue is sufficient for happiness."),
    ("Cleanthes", "The divine fire orders all things."),
    ("Cleanthes", "Reason is the common law of the universe."),

    ("Marcus Tullius Cicero", "A room without books is like a body without a soul."),
    ("Marcus Tullius Cicero", "If you have a garden and a library, you have everything you need."),
    ("Marcus Tullius Cicero", "The life of the dead is placed in the memory of the living."),
    ("Marcus Tullius Cicero", "Gratitude is not only the greatest of virtues, but the parent of all others."),
    ("Marcus Tullius Cicero", "Silence is one of the great arts of conversation."),
    ("Marcus Tullius Cicero",
     "Friendship improves happiness and abates misery, by the doubling of our joy and the dividing of our grief."),
    ("Marcus Tullius Cicero", "The first duty of a man is the seeking after and the investigation of truth."),
    ("Marcus Tullius Cicero", "To be ignorant of what occurred before you were born is to remain always a child."),
    ("Marcus Tullius Cicero", "The good of the people is the chief law."),
    ("Marcus Tullius Cicero", "While there is life there is hope."),

    ("Boethius", "In every adversity of fortune, to consider what is still left is a consolation."),
    ("Boethius",
     "Nothing is miserable unless you think it so; and on the other hand, nothing is happy unless you are content with it."),
    ("Boethius", "No one can ever be truly happy until he has achieved the good that is proper to him."),
    ("Boethius", "Whoever seeks truth should not be frightened by any consequences."),
    ("Boethius", "The most miserable person is the one who cannot control himself."),
    ("Boethius", "The human race is always in need of hope."),
    ("Boethius", "The more a man is attached to worldly things, the more he is subject to fortune."),
    ("Boethius", "All fortune is good fortune."),
    ("Boethius", "Nothing is more fleeting than the form of beauty."),
    ("Boethius", "You have not lost anything if you have not lost your virtue."),

    ("Blaise Pascal", "The heart has its reasons which reason knows not."),
    ("Blaise Pascal", "Man is only a reed, the weakest in nature, but he is a thinking reed."),
    ("Blaise Pascal", "All of humanity's problems stem from man's inability to sit quietly in a room alone."),
    ("Blaise Pascal", "We know the truth not only by the reason, but also by the heart."),
    ("Blaise Pascal", "The present is never our end."),
    ("Blaise Pascal", "The eternal silence of these infinite spaces frightens me."),
    ("Blaise Pascal", "It is not certain that everything is uncertain."),
    ("Blaise Pascal",
     "The last function of reason is to recognize that there are an infinity of things which surpass it."),
    ("Blaise Pascal", "Kind words do not cost much. Yet they accomplish much."),
    ("Blaise Pascal",
     "We are usually convinced more easily by reasons we have found ourselves than by those which have occurred to others."),

    ("Thomas Hobbes", "The life of man is solitary, poor, nasty, brutish, and short."),
    ("Thomas Hobbes", "Covenants, without the sword, are but words."),
    ("Thomas Hobbes", "Curiosity is the lust of the mind."),
    ("Thomas Hobbes", "The condition of man is a condition of war of everyone against everyone."),
    ("Thomas Hobbes", "Fear and I were born twins together."),
    ("Thomas Hobbes", "Science is the knowledge of consequences, and dependence of one fact upon another."),
    ("Thomas Hobbes", "Words are wise men's counters, they do but reckon by them."),
    ("Thomas Hobbes", "Hell is truth seen too late."),
    ("Thomas Hobbes", "Leisure is the mother of philosophy."),
    ("Thomas Hobbes", "Understanding is nothing else than conception caused by speech."),

    ("Gottfried Wilhelm Leibniz", "Love is that which makes another's happiness necessary to your own."),
    ("Gottfried Wilhelm Leibniz", "The present is pregnant with the future."),
    ("Gottfried Wilhelm Leibniz", "We live in the best of all possible worlds."),
    ("Gottfried Wilhelm Leibniz",
     "Music is the pleasure the human mind experiences from counting without being aware that it is counting."),
    ("Gottfried Wilhelm Leibniz", "Nothing takes place without sufficient reason."),
    ("Gottfried Wilhelm Leibniz", "The soul is the mirror of an indestructible universe."),
    ("Gottfried Wilhelm Leibniz", "The world is the best that could have been made."),
    ("Gottfried Wilhelm Leibniz", "There are two kinds of truths: truths of reasoning and truths of fact."),
    ("Gottfried Wilhelm Leibniz", "The pleasure we obtain from music comes from counting, but counting unconsciously."),
    ("Gottfried Wilhelm Leibniz", "To love is to find pleasure in the happiness of another."),

    ("George Berkeley", "Esse est percipi."),
    ("George Berkeley", "The truth is the cry of all, but the game of few."),
    ("George Berkeley",
     "A little philosophy inclineth man's mind to atheism, but depth in philosophy bringeth men's minds back to religion."),
    ("George Berkeley", "We perceive only ideas, not things themselves."),
    ("George Berkeley", "The objects of sense exist only when they are perceived."),
    ("George Berkeley", "Matter is an unnecessary hypothesis."),
    ("George Berkeley",
     "The same principles which at first view lead to skepticism may be employed to establish certainty."),
    ("George Berkeley", "We are not concerned with things themselves, but with the ideas we have of them."),
    ("George Berkeley", "There is no such thing as an unperceived material substance."),
    ("George Berkeley", "The objects of knowledge are ideas actually imprinted on the senses."),

    ("David Hume", "Custom is the great guide of human life."),
    ("David Hume", "Reason is the slave of the passions."),
    ("David Hume", "A wise man proportions his belief to the evidence."),
    ("David Hume", "Truth springs from argument amongst friends."),
    ("David Hume", "The rules of morality are not conclusions of our reason."),
    ("David Hume", "Beauty in things exists merely in the mind which contemplates them."),
    ("David Hume",
     "It is not contrary to reason to prefer the destruction of the whole world to the scratching of my finger."),
    ("David Hume", "Generally speaking, the errors in religion are dangerous; those in philosophy only ridiculous."),
    ("David Hume", "Nothing is more surprising than the easiness with which the many are governed by the few."),
    ("David Hume", "The sweetest and most inoffensive path of life leads through the avenues of science and learning."),

    ("Mary Wollstonecraft", "I do not wish women to have power over men; but over themselves."),
    ("Mary Wollstonecraft", "Strengthen the female mind by enlarging it, and there will be an end to blind obedience."),
    ("Mary Wollstonecraft", "It is justice, not charity, that is wanting in the world."),
    ("Mary Wollstonecraft", "The beginning is always today."),
    ("Mary Wollstonecraft", "I love man as my fellow; but his sceptre, real, or usurped, shall not be extended to me."),
    ("Mary Wollstonecraft", "The mind will ever be unstable that has only prejudices to rest on."),
    ("Mary Wollstonecraft",
     "Taught from their infancy that beauty is woman's sceptre, the mind shapes itself to the body."),
    ("Mary Wollstonecraft", "Virtue can only flourish among equals."),
    ("Mary Wollstonecraft", "Women ought to have representatives, instead of being arbitrarily governed."),
    ("Mary Wollstonecraft",
     "The divine right of husbands, like the divine right of kings, may, it is hoped, be contested without danger."),

    ("Arthur Schopenhauer", "Talent hits a target no one else can hit; genius hits a target no one else can see."),
    ("Arthur Schopenhauer", "The two enemies of human happiness are pain and boredom."),
    ("Arthur Schopenhauer", "Every man takes the limits of his own field of vision for the limits of the world."),
    ("Arthur Schopenhauer", "Compassion is the basis of morality."),
    ("Arthur Schopenhauer", "Mostly it is loss which teaches us about the worth of things."),
    ("Arthur Schopenhauer", "The greatest of follies is to sacrifice health for any other type of happiness."),
    ("Arthur Schopenhauer", "We forfeit three-fourths of ourselves in order to be like other people."),
    ("Arthur Schopenhauer", "The safest way of not being very miserable is not to expect to be very happy."),
    ("Arthur Schopenhauer", "Every truth passes through three stages before it is recognized."),
    ("Arthur Schopenhauer", "Life swings like a pendulum backward and forward between pain and boredom."),

    ("Søren Kierkegaard",
     "People understand me so poorly that they don't even understand my complaint about them not understanding me."),
    ("Søren Kierkegaard",
     "The most painful state of being is remembering the future, particularly the one you'll never have."),
    ("Søren Kierkegaard", "Purity of heart is to will one thing."),
    ("Søren Kierkegaard", "To dare is to lose one's footing momentarily. Not to dare is to lose oneself."),
    ("Søren Kierkegaard", "The tyrant dies and his rule is over; the martyr dies and his rule begins."),
    ("Søren Kierkegaard", "Face the facts of being what you are, for that is what changes what you are."),
    ("Søren Kierkegaard", "Life is not a problem to be solved, but a reality to be experienced."),
    ("Søren Kierkegaard",
     "The function of prayer is not to influence God, but rather to change the nature of the one who prays."),
    ("Søren Kierkegaard",
     "People demand freedom of speech as a compensation for the freedom of thought which they seldom use."),
    ("Søren Kierkegaard", "Anxiety is the dizziness of freedom."),

    ("John Dewey", "Education is not preparation for life; education is life itself."),
    ("John Dewey",
     "Failure is instructive. The person who really thinks learns quite as much from his failures as from his successes."),
    ("John Dewey", "Arriving at one goal is the starting point to another."),
    ("John Dewey", "Every great advance in science has issued from a new audacity of imagination."),
    ("John Dewey", "We do not learn from experience. We learn from reflecting on experience."),
    ("John Dewey", "The deepest urge in human nature is the craving to be important."),
    ("John Dewey", "A problem well put is half solved."),
    ("John Dewey",
     "The self is not something ready-made, but something in continuous formation through choice of action."),
    ("John Dewey", "Democracy is a way of life controlled by a working faith in the possibilities of human nature."),
    ("John Dewey", "The good man is the man who rules himself."),

    ("Bertrand Russell", "The good life is one inspired by love and guided by knowledge."),
    ("Bertrand Russell",
     "The trouble with the world is that the stupid are cocksure and the intelligent are full of doubt."),
    ("Bertrand Russell", "War does not determine who is right—only who is left."),
    ("Bertrand Russell", "Do not fear to be eccentric in opinion, for every opinion now accepted was once eccentric."),
    ("Bertrand Russell", "To conquer fear is the beginning of wisdom."),
    ("Bertrand Russell", "The secret of happiness is to face the fact that the world is horrible, horrible, horrible."),
    ("Bertrand Russell", "The only thing that will redeem mankind is cooperation."),
    ("Bertrand Russell", "Patriotism is the willingness to kill and be killed for trivial reasons."),
    ("Bertrand Russell",
     "The fundamental cause of trouble in the world today is that the stupid are cocksure while the intelligent are full of doubt."),
    ("Bertrand Russell", "Mathematics, rightly viewed, possesses not only truth, but supreme beauty."),

    ("Albert Camus", "In the midst of winter, I found there was, within me, an invincible summer."),
    ("Albert Camus", "Nobody realizes that some people expend tremendous energy merely to be normal."),
    ("Albert Camus", "Real generosity toward the future lies in giving all to the present."),
    ("Albert Camus", "You will never be happy if you continue to search for what happiness consists of."),
    ("Albert Camus", "Freedom is nothing else but a chance to be better."),
    ("Albert Camus", "The need to be right is the sign of a vulgar mind."),
    ("Albert Camus", "To be happy, we must not be too concerned with others."),
    ("Albert Camus", "Life is the sum of all your choices."),
    ("Albert Camus", "Live to the point of tears."),
    ("Albert Camus", "Autumn is a second spring when every leaf is a flower."),

    ("Valery Verkhov", "Do it the right way, don’t do it the wrong way."),

    ("Roland Barthes", "By undressing, the woman is simultaneously de-sexualized."),
    ("Roland Barthes", "The aim of striptease is not to bring something deeply hidden to light."),
    ("Roland Barthes", "Striptease is based on a contradiction."),
    ("Roland Barthes", "The birth of the reader must be ransomed by the death of the Author."),

    ("Vladimir Bekasov", "It's so dumb it's brilliant!"),
    ("David Foster Wallace", "The truth will set you free. But not until it is finished with you."),
    ("David Foster Wallace", "Everything takes time. Bees have to move very fast to stay still."),
    ("Hermann Hesse", "Every experience has its element of magic."),
    ("Hermann Hesse", "Learn what is to be taken seriously and laugh at the rest."),
    ("Hermann Hesse", "To achieve the possible, we must attempt the impossible again and again."),
    ("Eliud Kipchoge", "Only the disciplined ones in life are free. If you are undisciplined,"
                       " you are a slave to your moods and your passions."),

    ("Kurt Vonnegut", "So it goes."),
    ("Kurt Vonnegut", "You asked the impossible of a machine...and the machine complied."),
    ("Thomas Mann", "There are so many different kinds of stupidity, and cleverness is one of the worst."),
    ("Rainer Maria Rilke", "There is only one journey. Going inside yourself."),
    ("Julio Cortázar", "In quoting others, we cite ourselves."),
    ("Aldous Huxley", "Facts do not cease to exist because they are ignored."),
    ("Aldous Huxley", "Experience teaches only the teachable."),
    ("George Orwell", "Nothing was your own except the few cubic centimetres inside your skull."),
    ("Herman Melville", "Ignorance is the parent of fear."),
    ("Karl Popper", "Science may be described as the art of systematic oversimplification."),
    ("Karl Popper", "A theory that explains everything, explains nothing."),
    ("Karl Popper", "If you can't say it simply and clearly, keep quiet, and keep working on it till you can."),
    ("Karl Popper", "Relativism is one of the many crimes committed by intellectuals. It is a betrayal of reason and of humanity."),
    ("Ernest Hemingway", "We are all broken - that’s how the light gets in."),
    ("Albert Camus", "Always go too far, because that's where you'll find the truth."),
    ("Albert Camus", "You can't create experience, you undergo it."),
    ("Albert Camus", "We are all special cases."),
    ("John Steinbeck", "I wonder why progress looks so much like destruction."),
    ("John Steinbeck", "Man has a choice and it's a choice that makes him a man."),

    ("Elena Tupikina", "That’s why I’m a physicist rather than a chemist."),
    ("Elena Tupikina", "Fine."),
    ("Elena Tupikina", "[Profanity]"),
    ("Elena Tupikina", "We need to do something about this."),
    ("Elena Tupikina", "Report information."),
    ("Elena Tupikina", "Burn a girl? Suck it up."),

]
